name: remote ssh command
on:
  pull_request:
    types: [ closed ]
    branches: [ master, uat ]

jobs:
  DeployStaging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/uat'
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!

  DeployProd:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!
